<html>
<head><title>CockyHRManager</title>
<style type="text/css">
.auto-style1 {
	text-align: center;
}
</style>
</head>
<body>
<div align="center">
<form id="form1" runat="server">
	<div class="auto-style1">
		<br>
		<asp:Image id="Image1" runat="server" ImageUrl="./cocky590.png" width="100px" height="100px"/>
		<br><br><br><br>COCKY ENTERPRISES APP MANAGER<br>APP TYPE MAINTEANCE 
		SUMMARY <br><br>
		<div class="auto-style1">
			<asp:GridView id="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="id" DataSourceID="SqlDataSource1" Width="1408px" horizontalalign="Center" AllowPaging="True">
				<Columns>
					<asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" SortExpression="id">
					</asp:BoundField>
					<asp:BoundField DataField="apptype" HeaderText="apptype" SortExpression="apptype">
					</asp:BoundField>
					<asp:BoundField DataField="apptypedescription" HeaderText="apptypedescription" SortExpression="apptypedescription">
					</asp:BoundField>
				</Columns>
			</asp:GridView>
		</div>
	</div>
	<asp:SqlDataSource id="SqlDataSource1" runat="server" ConflictDetection="CompareAllValues" ConnectionString="Dsn=GEMPROD" DeleteCommand="DELETE FROM [gapptype] WHERE [id] = ? AND (([apptype] = ?) OR ([apptype] IS NULL AND ? IS NULL)) AND (([apptypedescription] = ?) OR ([apptypedescription] IS NULL AND ? IS NULL))" InsertCommand="INSERT INTO [gapptype] ([apptype], [apptypedescription]) VALUES (?, ?)" OldValuesParameterFormatString="original_{0}" ProviderName="System.Data.Odbc" SelectCommand="SELECT * FROM [gapptype]" UpdateCommand="UPDATE [gapptype] SET [apptype] = ?, [apptypedescription] = ? WHERE [id] = ? AND (([apptype] = ?) OR ([apptype] IS NULL AND ? IS NULL)) AND (([apptypedescription] = ?) OR ([apptypedescription] IS NULL AND ? IS NULL))">
		<DeleteParameters>
			<asp:Parameter Name="original_id" Type="Int32" />
			<asp:Parameter Name="original_apptype" Type="Int32" />
			<asp:Parameter Name="original_apptype" Type="Int32" />
			<asp:Parameter Name="original_apptypedescription" Type="String" />
			<asp:Parameter Name="original_apptypedescription" Type="String" />
		</DeleteParameters>
		<InsertParameters>
			<asp:Parameter Name="apptype" Type="Int32" />
			<asp:Parameter Name="apptypedescription" Type="String" />
		</InsertParameters>
		<UpdateParameters>
			<asp:Parameter Name="apptype" Type="Int32" />
			<asp:Parameter Name="apptypedescription" Type="String" />
			<asp:Parameter Name="original_id" Type="Int32" />
			<asp:Parameter Name="original_apptype" Type="Int32" />
			<asp:Parameter Name="original_apptype" Type="Int32" />
			<asp:Parameter Name="original_apptypedescription" Type="String" />
			<asp:Parameter Name="original_apptypedescription" Type="String" />
		</UpdateParameters>
	</asp:SqlDataSource>
</form>
<span><a href="insertapptypes.aspx">Insert a New App Type</a><BR></span>
<BR>
<HR>
<span><a href="index.aspx">ReturnToManagerHome</a><BR></span>
<HR>
</div>
</body>
</html>