<html>
<head><title>CockyHRManager</title>
<style type="text/css">
.auto-style1 {
	text-align: center;
}
</style>
</head>
<body>
<div align="center">
<form id="form1" runat="server">
	<div class="auto-style1">
		<br>
		<asp:Image id="Image1" runat="server" ImageUrl="./cocky590.png" width="100px" height="100px"/>
		<br><br><br><br>COCKY ENTERPRISES <br>VOICE TRUNK MANAGER <br><br>
		<div class="auto-style1">
			<asp:GridView id="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="id" DataSourceID="SqlDataSource1" Width="1408px" horizontalalign="Center" AllowPaging="True">
				<Columns>
					<asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" SortExpression="id">
					</asp:BoundField>
					<asp:BoundField DataField="trunkid" HeaderText="trunkid" SortExpression="trunkid">
					</asp:BoundField>
					<asp:BoundField DataField="trunktypeid" HeaderText="trunktypeid" SortExpression="trunktypeid">
					</asp:BoundField>
					<asp:BoundField DataField="description" HeaderText="description" SortExpression="description">
					</asp:BoundField>
				</Columns>
			</asp:GridView>
		</div>
	</div>
	<asp:SqlDataSource id="SqlDataSource1" runat="server" ConflictDetection="CompareAllValues" ConnectionString="Dsn=GEMPROD" DeleteCommand="DELETE FROM [gvoicetrunks] WHERE [id] = ? AND (([trunkid] = ?) OR ([trunkid] IS NULL AND ? IS NULL)) AND (([trunktypeid] = ?) OR ([trunktypeid] IS NULL AND ? IS NULL)) AND (([description] = ?) OR ([description] IS NULL AND ? IS NULL))" InsertCommand="INSERT INTO [gvoicetrunks] ([trunkid], [trunktypeid], [description]) VALUES (?, ?, ?)" OldValuesParameterFormatString="original_{0}" ProviderName="System.Data.Odbc" SelectCommand="SELECT * FROM [gvoicetrunks]" UpdateCommand="UPDATE [gvoicetrunks] SET [trunkid] = ?, [trunktypeid] = ?, [description] = ? WHERE [id] = ? AND (([trunkid] = ?) OR ([trunkid] IS NULL AND ? IS NULL)) AND (([trunktypeid] = ?) OR ([trunktypeid] IS NULL AND ? IS NULL)) AND (([description] = ?) OR ([description] IS NULL AND ? IS NULL))">
		<DeleteParameters>
			<asp:Parameter Name="original_id" Type="Int32" />
			<asp:Parameter Name="original_trunkid" Type="String" />
			<asp:Parameter Name="original_trunkid" Type="String" />
			<asp:Parameter Name="original_trunktypeid" Type="Int32" />
			<asp:Parameter Name="original_trunktypeid" Type="Int32" />
			<asp:Parameter Name="original_description" Type="String" />
			<asp:Parameter Name="original_description" Type="String" />
		</DeleteParameters>
		<InsertParameters>
			<asp:Parameter Name="trunkid" Type="String" />
			<asp:Parameter Name="trunktypeid" Type="Int32" />
			<asp:Parameter Name="description" Type="String" />
		</InsertParameters>
		<UpdateParameters>
			<asp:Parameter Name="trunkid" Type="String" />
			<asp:Parameter Name="trunktypeid" Type="Int32" />
			<asp:Parameter Name="description" Type="String" />
			<asp:Parameter Name="original_id" Type="Int32" />
			<asp:Parameter Name="original_trunkid" Type="String" />
			<asp:Parameter Name="original_trunkid" Type="String" />
			<asp:Parameter Name="original_trunktypeid" Type="Int32" />
			<asp:Parameter Name="original_trunktypeid" Type="Int32" />
			<asp:Parameter Name="original_description" Type="String" />
			<asp:Parameter Name="original_description" Type="String" />
		</UpdateParameters>
	</asp:SqlDataSource>
</form>
<span><a href="insertcompany.aspx">Insert a New Voice Trunk</a><BR></span>
<BR>
<HR>
<span><a href="index.aspx">ReturnToManagerHome</a><BR></span>
<HR>
</div>
</body>
</html>