<html>
<head><title>CockyHRManager</title>
<style type="text/css">
.auto-style1 {
	text-align: center;
}
</style>
</head>
<body>
<div align="center">
<form id="form1" runat="server">
	<div class="auto-style1">
		<br>
		<asp:Image id="Image1" runat="server" ImageUrl="./cocky590.png" width="100px" height="100px"/>
		<br><br><br><br>COCKY ENTERPRISES <br>TELEPHONE NUMBER MANAGER <br><br>
		<div class="auto-style1">
			<asp:GridView id="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="id" DataSourceID="SqlDataSource1" Width="1408px" horizontalalign="Center" AllowPaging="True">
				<Columns>
					<asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" SortExpression="id">
					</asp:BoundField>
					<asp:BoundField DataField="tn" HeaderText="tn" SortExpression="tn">
					</asp:BoundField>
					<asp:BoundField DataField="phoneid" HeaderText="phoneid" SortExpression="phoneid">
					</asp:BoundField>
					<asp:BoundField DataField="channelid" HeaderText="channelid" SortExpression="channelid">
					</asp:BoundField>
					<asp:BoundField DataField="description" HeaderText="description" SortExpression="description">
					</asp:BoundField>
				</Columns>
			</asp:GridView>
		</div>
	</div>
	<asp:SqlDataSource id="SqlDataSource1" runat="server" ConflictDetection="CompareAllValues" ConnectionString="Dsn=GEMPROD" DeleteCommand="DELETE FROM [gtelephonenumber] WHERE [id] = ? AND (([tn] = ?) OR ([tn] IS NULL AND ? IS NULL)) AND (([phoneid] = ?) OR ([phoneid] IS NULL AND ? IS NULL)) AND (([channelid] = ?) OR ([channelid] IS NULL AND ? IS NULL)) AND (([description] = ?) OR ([description] IS NULL AND ? IS NULL))" InsertCommand="INSERT INTO [gtelephonenumber] ([tn], [phoneid], [channelid], [description]) VALUES (?, ?, ?, ?)" OldValuesParameterFormatString="original_{0}" ProviderName="System.Data.Odbc" SelectCommand="SELECT * FROM [gtelephonenumber]" UpdateCommand="UPDATE [gtelephonenumber] SET [tn] = ?, [phoneid] = ?, [channelid] = ?, [description] = ? WHERE [id] = ? AND (([tn] = ?) OR ([tn] IS NULL AND ? IS NULL)) AND (([phoneid] = ?) OR ([phoneid] IS NULL AND ? IS NULL)) AND (([channelid] = ?) OR ([channelid] IS NULL AND ? IS NULL)) AND (([description] = ?) OR ([description] IS NULL AND ? IS NULL))">
		<DeleteParameters>
			<asp:Parameter Name="original_id" Type="Int32" />
			<asp:Parameter Name="original_tn" Type="String" />
			<asp:Parameter Name="original_tn" Type="String" />
			<asp:Parameter Name="original_phoneid" Type="Int32" />
			<asp:Parameter Name="original_phoneid" Type="Int32" />
			<asp:Parameter Name="original_channelid" Type="Int32" />
			<asp:Parameter Name="original_channelid" Type="Int32" />
			<asp:Parameter Name="original_description" Type="String" />
			<asp:Parameter Name="original_description" Type="String" />
		</DeleteParameters>
		<InsertParameters>
			<asp:Parameter Name="tn" Type="String" />
			<asp:Parameter Name="phoneid" Type="Int32" />
			<asp:Parameter Name="channelid" Type="Int32" />
			<asp:Parameter Name="description" Type="String" />
		</InsertParameters>
		<UpdateParameters>
			<asp:Parameter Name="tn" Type="String" />
			<asp:Parameter Name="phoneid" Type="Int32" />
			<asp:Parameter Name="channelid" Type="Int32" />
			<asp:Parameter Name="description" Type="String" />
			<asp:Parameter Name="original_id" Type="Int32" />
			<asp:Parameter Name="original_tn" Type="String" />
			<asp:Parameter Name="original_tn" Type="String" />
			<asp:Parameter Name="original_phoneid" Type="Int32" />
			<asp:Parameter Name="original_phoneid" Type="Int32" />
			<asp:Parameter Name="original_channelid" Type="Int32" />
			<asp:Parameter Name="original_channelid" Type="Int32" />
			<asp:Parameter Name="original_description" Type="String" />
			<asp:Parameter Name="original_description" Type="String" />
		</UpdateParameters>
	</asp:SqlDataSource>
</form>
<span><a href="inserttn.aspx">Insert a New Telephone Number</a><BR></span>
<BR>
<HR>
<span><a href="index.aspx">ReturnToManagerHome</a><BR></span>
<HR>
</div>
</body>
</html>