<html>
<head><title>CockyHRManager</title>
<style type="text/css">
.auto-style1 {
	text-align: center;
}
</style>
</head>
<body>
<div align="center">
<form id="form1" runat="server">
	<div class="auto-style1">
		<br>
		<asp:Image id="Image1" runat="server" ImageUrl="./cocky590.png" width="100px" height="100px"/>
		<br><br><br><br>COCKY ENTERPRISES APP MANAGER <br><br>
		<div class="auto-style1">
			<asp:GridView id="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="id" DataSourceID="SqlDataSource1" Width="1408px" horizontalalign="Center" AllowPaging="True">
				<Columns>
					<asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" SortExpression="id" InsertVisible="False">
					</asp:BoundField>
					<asp:BoundField DataField="topologyid" HeaderText="topologyid" SortExpression="topologyid">
					</asp:BoundField>
					<asp:BoundField DataField="topologydescription" HeaderText="topologydescription" SortExpression="topologydescription">
					</asp:BoundField>
				</Columns>
			</asp:GridView>
		</div>
	</div>
	<asp:SqlDataSource id="SqlDataSource1" runat="server" ConflictDetection="CompareAllValues" ConnectionString="Dsn=GEMPROD" DeleteCommand="DELETE FROM [ggridtopology] WHERE [id] = ? AND (([topologyid] = ?) OR ([topologyid] IS NULL AND ? IS NULL)) AND (([topologydescription] = ?) OR ([topologydescription] IS NULL AND ? IS NULL))" InsertCommand="INSERT INTO [ggridtopology] ([topologyid], [topologydescription]) VALUES (?, ?)" OldValuesParameterFormatString="original_{0}" ProviderName="System.Data.Odbc" SelectCommand="SELECT * FROM [ggridtopology]" UpdateCommand="UPDATE [ggridtopology] SET [topologyid] = ?, [topologydescription] = ? WHERE [id] = ? AND (([topologyid] = ?) OR ([topologyid] IS NULL AND ? IS NULL)) AND (([topologydescription] = ?) OR ([topologydescription] IS NULL AND ? IS NULL))">
		<DeleteParameters>
			<asp:Parameter Name="original_id" Type="Int32" />
			<asp:Parameter Name="original_topologyid" Type="String" />
			<asp:Parameter Name="original_topologyid" Type="String" />
			<asp:Parameter Name="original_topologydescription" Type="String" />
			<asp:Parameter Name="original_topologydescription" Type="String" />
		</DeleteParameters>
		<InsertParameters>
			<asp:Parameter Name="topologyid" Type="String" />
			<asp:Parameter Name="topologydescription" Type="String" />
		</InsertParameters>
		<UpdateParameters>
			<asp:Parameter Name="topologyid" Type="String" />
			<asp:Parameter Name="topologydescription" Type="String" />
			<asp:Parameter Name="original_id" Type="Int32" />
			<asp:Parameter Name="original_topologyid" Type="String" />
			<asp:Parameter Name="original_topologyid" Type="String" />
			<asp:Parameter Name="original_topologydescription" Type="String" />
			<asp:Parameter Name="original_topologydescription" Type="String" />
		</UpdateParameters>
	</asp:SqlDataSource>
</form>
<span><a href="insertgridtopology.aspx">Insert a GridTopology</a><BR></span>
<BR>
<HR>
<span><a href="index.aspx">ReturnToManagerHome</a><BR></span>
<HR>
</div>
</body>
</html>