<html>
<head><title>CockyMoviesManager</title>
<style type="text/css" class="rowstyle">
.auto-style1 {
	text-align: center;
}
.rowstyle
{
	width:120px;
}
</style>
</head>
<body>
<form id="form1" runat="server">
	<div class="auto-style1">
		<br>
		<asp:Image id="Image1" runat="server" ImageUrl="./images/cocky590.png" Width="100px" Height="100px"/>
		<br><br><br><br>COCKY ENTERPRISES BRANCH MANAGER <br><br><br>
		<div class="auto-style1" align="center" contenteditable="true">
			<asp:GridView id="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="id" DataSourceID="SqlDataSource1" Width="1408px" AllowPaging="True" Font-Size="10pt" horizontalalign="Center">
				<Columns>
					<asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" SortExpression="id">
					</asp:BoundField>
					<asp:BoundField DataField="branchid" HeaderText="branchid" SortExpression="branchid">
					</asp:BoundField>
					<asp:BoundField DataField="brancdescription" HeaderText="brancdescription" SortExpression="brancdescription">
					</asp:BoundField>
					<asp:BoundField DataField="siteid" HeaderText="siteid" SortExpression="siteid">
					</asp:BoundField>
				</Columns><RowStyle CssClass="rowstyle"></RowStyle>
			</asp:GridView>
		</div>
	</div>
	<asp:SqlDataSource id="SqlDataSource1" runat="server" ConnectionString="Dsn=GEMPROD" DeleteCommand="DELETE FROM [gbranches] WHERE [id] = ? AND (([branchid] = ?) OR ([branchid] IS NULL AND ? IS NULL)) AND (([brancdescription] = ?) OR ([brancdescription] IS NULL AND ? IS NULL)) AND (([siteid] = ?) OR ([siteid] IS NULL AND ? IS NULL))" InsertCommand="INSERT INTO [gbranches] ([branchid], [brancdescription], [siteid]) VALUES (?, ?, ?)" OldValuesParameterFormatString="original_{0}" ProviderName="System.Data.Odbc" SelectCommand="SELECT * FROM [gbranches]" UpdateCommand="UPDATE [gbranches] SET [branchid] = ?, [brancdescription] = ?, [siteid] = ? WHERE [id] = ? AND (([branchid] = ?) OR ([branchid] IS NULL AND ? IS NULL)) AND (([brancdescription] = ?) OR ([brancdescription] IS NULL AND ? IS NULL)) AND (([siteid] = ?) OR ([siteid] IS NULL AND ? IS NULL))" ConflictDetection="CompareAllValues">
		<DeleteParameters>
			<asp:Parameter Name="original_id" Type="Int32" />
			<asp:Parameter Name="original_branchid" Type="String" />
			<asp:Parameter Name="original_branchid" Type="String" />
			<asp:Parameter Name="original_brancdescription" Type="String" />
			<asp:Parameter Name="original_brancdescription" Type="String" />
			<asp:Parameter Name="original_siteid" Type="String" />
			<asp:Parameter Name="original_siteid" Type="String" />
		</DeleteParameters>
		<InsertParameters>
			<asp:Parameter Name="branchid" Type="String" />
			<asp:Parameter Name="brancdescription" Type="String" />
			<asp:Parameter Name="siteid" Type="String" />
		</InsertParameters>
		<UpdateParameters>
			<asp:Parameter Name="branchid" Type="String" />
			<asp:Parameter Name="brancdescription" Type="String" />
			<asp:Parameter Name="siteid" Type="String" />
			<asp:Parameter Name="original_id" Type="Int32" />
			<asp:Parameter Name="original_branchid" Type="String" />
			<asp:Parameter Name="original_branchid" Type="String" />
			<asp:Parameter Name="original_brancdescription" Type="String" />
			<asp:Parameter Name="original_brancdescription" Type="String" />
			<asp:Parameter Name="original_siteid" Type="String" />
			<asp:Parameter Name="original_siteid" Type="String" />
		</UpdateParameters>
	</asp:SqlDataSource>

<div><a href="insertstore.aspx">Insert a New Branch</a></div>

</form>

</body>
</html>