<html>
<head><title>CockyHRManager</title>
<style type="text/css">
.auto-style1 {
	text-align: center;
}
</style>
</head>
<body>
<div align="center">
<form id="form1" runat="server">
	<div class="auto-style1">
		<br>
		<asp:Image id="Image1" runat="server" ImageUrl="./cocky590.png" width="100px" height="100px"/>
		<br><br><br><br>COCKY ENTERPRISES <br>HOSTING ACCOUNTS <br><br>
		<div class="auto-style1">
			<asp:GridView id="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="id" DataSourceID="SqlDataSource1" Width="1408px" horizontalalign="Center" AllowPaging="True">
				<Columns>
					<asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" SortExpression="id">
					</asp:BoundField>
					<asp:BoundField DataField="accountname" HeaderText="accountname" SortExpression="accountname">
					</asp:BoundField>
					<asp:BoundField DataField="companyid" HeaderText="companyid" SortExpression="companyid">
					</asp:BoundField>
					<asp:BoundField DataField="wholesalevendorid" HeaderText="wholesalevendorid" SortExpression="wholesalevendorid">
					</asp:BoundField>
				</Columns>
			</asp:GridView>
		</div>
	</div>
	<asp:SqlDataSource id="SqlDataSource1" runat="server" ConflictDetection="CompareAllValues" ConnectionString="Dsn=GEMPROD" DeleteCommand="DELETE FROM [gaccounts] WHERE [id] = ? AND (([accountname] = ?) OR ([accountname] IS NULL AND ? IS NULL)) AND (([companyid] = ?) OR ([companyid] IS NULL AND ? IS NULL)) AND (([wholesalevendorid] = ?) OR ([wholesalevendorid] IS NULL AND ? IS NULL))" InsertCommand="INSERT INTO [gaccounts] ([accountname], [companyid], [wholesalevendorid]) VALUES (?, ?, ?)" OldValuesParameterFormatString="original_{0}" ProviderName="System.Data.Odbc" SelectCommand="SELECT * FROM [gaccounts]" UpdateCommand="UPDATE [gaccounts] SET [accountname] = ?, [companyid] = ?, [wholesalevendorid] = ? WHERE [id] = ? AND (([accountname] = ?) OR ([accountname] IS NULL AND ? IS NULL)) AND (([companyid] = ?) OR ([companyid] IS NULL AND ? IS NULL)) AND (([wholesalevendorid] = ?) OR ([wholesalevendorid] IS NULL AND ? IS NULL))">
		<DeleteParameters>
			<asp:Parameter Name="original_id" Type="Int64" />
			<asp:Parameter Name="original_accountname" Type="String" />
			<asp:Parameter Name="original_accountname" Type="String" />
			<asp:Parameter Name="original_companyid" Type="Int32" />
			<asp:Parameter Name="original_companyid" Type="Int32" />
			<asp:Parameter Name="original_wholesalevendorid" Type="Int32" />
			<asp:Parameter Name="original_wholesalevendorid" Type="Int32" />
		</DeleteParameters>
		<InsertParameters>
			<asp:Parameter Name="accountname" Type="String" />
			<asp:Parameter Name="companyid" Type="Int32" />
			<asp:Parameter Name="wholesalevendorid" Type="Int32" />
		</InsertParameters>
		<UpdateParameters>
			<asp:Parameter Name="accountname" Type="String" />
			<asp:Parameter Name="companyid" Type="Int32" />
			<asp:Parameter Name="wholesalevendorid" Type="Int32" />
			<asp:Parameter Name="original_id" Type="Int64" />
			<asp:Parameter Name="original_accountname" Type="String" />
			<asp:Parameter Name="original_accountname" Type="String" />
			<asp:Parameter Name="original_companyid" Type="Int32" />
			<asp:Parameter Name="original_companyid" Type="Int32" />
			<asp:Parameter Name="original_wholesalevendorid" Type="Int32" />
			<asp:Parameter Name="original_wholesalevendorid" Type="Int32" />
		</UpdateParameters>
	</asp:SqlDataSource>
</form>
<span><a href="insertnewhostingaccount.aspx">Insert a New Hosting Account</a><BR></span>
<BR>
<HR>
<span><a href="index.aspx">ReturnToManagerHome</a><BR></span>
<HR>
</div>
</body>
</html>