<html>
<head><title>CockyHRManager</title>
<style type="text/css">
.auto-style1 {
	text-align: center;
}
</style>
</head>
<body>
<div align="center">
<form id="form1" runat="server">
	<div class="auto-style1">
		<br>
		<asp:Image id="Image1" runat="server" ImageUrl="./cocky590.png" width="100px" height="100px"/>
		<br><br><br><br>COCKY ENTERPRISES <br>USER GROUPS<br><br>
		<div class="auto-style1">
			<asp:GridView id="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="id" DataSourceID="SqlDataSource1" Width="1408px" horizontalalign="Center" AllowPaging="True">
				<Columns>
					<asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" SortExpression="id">
					</asp:BoundField>
					<asp:BoundField DataField="groupname" HeaderText="groupname" SortExpression="groupname">
					</asp:BoundField>
					<asp:BoundField DataField="groupid" HeaderText="groupid" SortExpression="groupid">
					</asp:BoundField>
				</Columns>
			</asp:GridView>
		</div>
	</div>
	<asp:SqlDataSource id="SqlDataSource1" runat="server" ConflictDetection="CompareAllValues" ConnectionString="Dsn=GEMPROD" DeleteCommand="DELETE FROM [gusergroups] WHERE [id] = ? AND (([groupname] = ?) OR ([groupname] IS NULL AND ? IS NULL)) AND (([groupid] = ?) OR ([groupid] IS NULL AND ? IS NULL))" InsertCommand="INSERT INTO [gusergroups] ([groupname], [groupid]) VALUES (?, ?)" OldValuesParameterFormatString="original_{0}" ProviderName="System.Data.Odbc" SelectCommand="SELECT * FROM [gusergroups]" UpdateCommand="UPDATE [gusergroups] SET [groupname] = ?, [groupid] = ? WHERE [id] = ? AND (([groupname] = ?) OR ([groupname] IS NULL AND ? IS NULL)) AND (([groupid] = ?) OR ([groupid] IS NULL AND ? IS NULL))">
		<DeleteParameters>
			<asp:Parameter Name="original_id" Type="Int64" />
			<asp:Parameter Name="original_groupname" Type="String" />
			<asp:Parameter Name="original_groupname" Type="String" />
			<asp:Parameter Name="original_groupid" Type="String" />
			<asp:Parameter Name="original_groupid" Type="String" />
		</DeleteParameters>
		<InsertParameters>
			<asp:Parameter Name="groupname" Type="String" />
			<asp:Parameter Name="groupid" Type="String" />
		</InsertParameters>
		<UpdateParameters>
			<asp:Parameter Name="groupname" Type="String" />
			<asp:Parameter Name="groupid" Type="String" />
			<asp:Parameter Name="original_id" Type="Int64" />
			<asp:Parameter Name="original_groupname" Type="String" />
			<asp:Parameter Name="original_groupname" Type="String" />
			<asp:Parameter Name="original_groupid" Type="String" />
			<asp:Parameter Name="original_groupid" Type="String" />
		</UpdateParameters>
	</asp:SqlDataSource>
</form>
<span><a href="insertusergroup.aspx">Insert a New User Groups</a><BR></span>
<BR>
<HR>
<span><a href="index.aspx">ReturnToManagerHome</a><BR></span>
<HR>
</div>
</body>
</html>