<html>
<head><title>CockyHRManager</title>
<style type="text/css">
.auto-style1 {
	text-align: center;
}
</style>
</head>
<body>
<div align="center">
<form id="form1" runat="server">
	<div class="auto-style1">
		<br>
		<asp:Image id="Image1" runat="server" ImageUrl="./cocky590.png" Height="126px" Width="156px" />
		<br><br><br><br>COCKY ENTERPRISES EMPLOYEE MANAGER - COLUMBIA, SC<br>2300 FORREST 
		DRIVE<br><br>
		<div class="auto-style1">
			<asp:GridView id="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="id" DataSourceID="SqlDataSource1" Width="1276px" horizontalalign="Center" AllowPaging="True" Font-Size="10pt">
				<Columns>
					<asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" SortExpression="id">
					</asp:BoundField>
					<asp:BoundField DataField="employeeid" HeaderText="employeeid" SortExpression="employeeid">
					</asp:BoundField>
					<asp:BoundField DataField="fullname" HeaderText="fullname" SortExpression="fullname">
					</asp:BoundField>
					<asp:BoundField DataField="primarysite" HeaderText="primarysite" SortExpression="primarysite">
					</asp:BoundField>
					<asp:BoundField DataField="homeoffice" HeaderText="homeoffice" SortExpression="homeoffice">
					</asp:BoundField>
				</Columns>
			</asp:GridView>
		</div>
	</div>
	<asp:SqlDataSource id="SqlDataSource1" runat="server" ConflictDetection="CompareAllValues" ConnectionString="Dsn=GEMPROD" DeleteCommand="DELETE FROM [gemployees] WHERE [id] = ? AND (([employeeid] = ?) OR ([employeeid] IS NULL AND ? IS NULL)) AND (([fullname] = ?) OR ([fullname] IS NULL AND ? IS NULL)) AND (([primarysite] = ?) OR ([primarysite] IS NULL AND ? IS NULL)) AND (([homeoffice] = ?) OR ([homeoffice] IS NULL AND ? IS NULL))" InsertCommand="INSERT INTO [gemployees] ([employeeid], [fullname], [primarysite], [homeoffice]) VALUES (?, ?, ?, ?)" OldValuesParameterFormatString="original_{0}" ProviderName="System.Data.Odbc" SelectCommand="SELECT * FROM [gemployees]" UpdateCommand="UPDATE [gemployees] SET [employeeid] = ?, [fullname] = ?, [primarysite] = ?, [homeoffice] = ? WHERE [id] = ? AND (([employeeid] = ?) OR ([employeeid] IS NULL AND ? IS NULL)) AND (([fullname] = ?) OR ([fullname] IS NULL AND ? IS NULL)) AND (([primarysite] = ?) OR ([primarysite] IS NULL AND ? IS NULL)) AND (([homeoffice] = ?) OR ([homeoffice] IS NULL AND ? IS NULL))">
		<DeleteParameters>
			<asp:Parameter Name="original_id" Type="Int32" />
			<asp:Parameter Name="original_employeeid" Type="String" />
			<asp:Parameter Name="original_employeeid" Type="String" />
			<asp:Parameter Name="original_fullname" Type="String" />
			<asp:Parameter Name="original_fullname" Type="String" />
			<asp:Parameter Name="original_primarysite" Type="String" />
			<asp:Parameter Name="original_primarysite" Type="String" />
			<asp:Parameter Name="original_homeoffice" Type="String" />
			<asp:Parameter Name="original_homeoffice" Type="String" />
		</DeleteParameters>
		<InsertParameters>
			<asp:Parameter Name="employeeid" Type="String" />
			<asp:Parameter Name="fullname" Type="String" />
			<asp:Parameter Name="primarysite" Type="String" />
			<asp:Parameter Name="homeoffice" Type="String" />
		</InsertParameters>
		<UpdateParameters>
			<asp:Parameter Name="employeeid" Type="String" />
			<asp:Parameter Name="fullname" Type="String" />
			<asp:Parameter Name="primarysite" Type="String" />
			<asp:Parameter Name="homeoffice" Type="String" />
			<asp:Parameter Name="original_id" Type="Int32" />
			<asp:Parameter Name="original_employeeid" Type="String" />
			<asp:Parameter Name="original_employeeid" Type="String" />
			<asp:Parameter Name="original_fullname" Type="String" />
			<asp:Parameter Name="original_fullname" Type="String" />
			<asp:Parameter Name="original_primarysite" Type="String" />
			<asp:Parameter Name="original_primarysite" Type="String" />
			<asp:Parameter Name="original_homeoffice" Type="String" />
			<asp:Parameter Name="original_homeoffice" Type="String" />
		</UpdateParameters>
	</asp:SqlDataSource>
</form>
<span><a href="insertemp.aspx">Insert a New Employee</a><BR></span>
<BR>
<HR>
<span><a href="index.aspx">ReturnToManagerHome</a><BR></span>
<HR>
</div>
</body>
</html>