/* GEM - GridManager - Updated Schema - For CTS Consulting */
\CONNECT GEM;
CREATE TABLE GUSERS(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, jid int, USERID VARCHAR(20), FIRSTNAME VARCHAR(20) NOT NULL, LASTNAME VARCHAR(20) NOT NULL, USERNAME VARCHAR(100), PHONE VARCHAR(20), EMAIL VARCHAR(100), ADDRESS1 VARCHAR(50), ADDRESS2 VARCHAR(50), CITY VARCHAR(50), REGION VARCHAR(50), POSTAL VARCHAR(20), COUNTRY VARCHAR(50), FAXNUMBER VARCHAR(20), CARDNUMBER VARCHAR(50), EXPIRECARD VARCHAR(10),SECURITYCARD VARCHAR(3), NAMEONCARD VARCHAR(100), CARDADDRESS1 VARCHAR(50), CARDADDRESS2 VARCHAR(50), CARDZIP VARCHAR(50), CARDREGION VARCHAR(50), CARDCITY VARCHAR(50), CARDCOUNTRY VARCHAR(50), FIRSTPRODUCT VARCHAR(50), registrationDate VARCHAR(50), SSDUNS VARCHAR(50), SECONDPRODUCT VARCHAR(50), KEYTYPE VARCHAR(50), CELLPHONE VARCHAR(50), CORPORATENAME VARCHAR(50), FULLNAME VARCHAR(50));  
CREATE TABLE GUSERS_CARDS(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, USERID VARCHAR(20), APPID VARCHAR(50), CARDNAME VARCHAR(50), CARDTYPE VARCHAR(50), CARDNUMBER VARCHAR(50), CARDEXPIRATION VARCHAR(15), CARDSECURITY VARCHAR(15), APPDATE DATE); 
CREATE TABLE GPRODUCTS(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, PRODUCTID INT , PRODUCTNAME CHAR(50), PRODUCT_WOO_ID CHAR(50), PROUDCT_WOO_INSTANCE CHAR(100), PRODUCT_WOO_URL CHAR(250), VENDORID CHAR(25), ORACLEID CHAR(50), DYNAMICSID CHAR(50), DIVISION CHAR(30)); 
CREATE TABLE GITSM(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, TICKETID BIGINT, CUSTID CHAR(100), ORACLEID CHAR(100), DYNAMICSID CHAR(100), SUMMARY CHAR(200), PRIORITY CHAR(10), RES1 CHAR(100), RES2 CHAR(100), RES3 CHAR(100), RES4 CHAR(100), TICKETSTATUS CHAR(100), OPENDATE DATE, CLOSEDATE DATE); 
CREATE TABLE GITSM_DETAIL(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, DETAILID BIGINT , TICKETID BIGINT, LINENUMBER CHAR(50), LINEDETAIL CHAR(1000));
CREATE TABLE GCHANGE(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, CHANGEID BIGINT, WORKEFFORTSIZE CHAR(25), BUSUNIT CHAR(25), ENGINEERID CHAR(50), DESCRIPTION CHAR(3500), STATUS CHAR(10), APPROVALID CHAR(100), CHANGESTART DATE, CHANGEEND DATE, HOLDINFO CHAR(1000), COMMENTS CHAR(3000));
CREATE TABLE GHREGIONS(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, REGIONID VARCHAR(100), REGIONDESCRIPTION VARCHAR(200));
CREATE TABLE GBREGIONS(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, REGIONID VARCHAR(100), REGIONDESCRIPTION VARCHAR(200));
CREATE TABLE GBRANCHES(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, BRANCHID VARCHAR(100), BRANCDESCRIPTION VARCHAR(200), SITEID VARCHAR(50));
CREATE TABLE GSITES(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, SITEID VARCHAR(100), SITEDESCRIPTION VARCHAR(200), SITECLLI VARCHAR(100), ADDRESS1 VARCHAR(150), ADDRESS2 VARCHAR(150), STATEREGION VARCHAR(150), POSTAL VARCHAR(150), PHONE VARCHAR(100), FAX VARCHAR(100), SITECONTACTID int);
CREATE TABLE GMANAGERS(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, MANAGERID VARCHAR(100), FULLNAME VARCHAR(200));
CREATE TABLE GEMPLOYEES(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, EMPLOYEEID VARCHAR(100), FULLNAME VARCHAR(200), PRIMARYSITE VARCHAR(100), HOMEOFFICE VARCHAR(100));


/03/16/ADDS [All the Screens For App Type]

create table gapps(id int primary key GENERATED BY DEFAULT AS IDENTITY, appid varchar(150), appdescription varchar(500), apptype int, appregion int, dbmstype varchar(100), dbmsvendor varchar(100), dbmstopology varchar(100), gridid int); 
create table gapptype(id int primary key GENERATED BY DEFAULT AS IDENTITY, apptype int, apptypedescription varchar(150)); 
create table gdbmstype(id int primary key GENERATED BY DEFAULT AS IDENTITY, dbmstype int, dbmstypedescription varchar(150)); 
create table gdbmstopology(id int primary key GENERATED BY DEFAULT AS IDENTITY, dbmstopology int, dbmstopologydescription varchar(150));
create table gserver(id int primary key GENERATED BY DEFAULT AS IDENTITY, description varchar(255), siteid int, primaryip varchar(250)); 
create table grouter(id int primary key GENERATED BY DEFAULT AS IDENTITY, description varchar(255), siteid int, primaryip varchar(250)); 
create table gswitch(id int primary key GENERATED BY DEFAULT AS IDENTITY, description varchar(255), siteid int, primaryip varchar(250)); 

03/23/ADDS EXPANSIVE
create table ggridroots(id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, siteid int, rackid int, locationid int, floorid int, ipaddress varchar(150), telemetryip varchar(150)); 
create table ggridnodes(id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, siteid int, rackid int, locationid int, floorid int, ipaddress varchar(150), telemetryip varchar(150), rootid1 int, rootid2 int); 
create table ggrids (id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, geometry varchar(100), gridsite1 int, gridnode1id int, gridsite2 int, gridnode2id int, gridsite3 int, gridnode3id int, gridsite4 int, gridnode4id int, gridsite5 int, gridnode5id int, gridsite6 int, gridnode6id int, drsite1 int, drnode1id int, drsite2 int, drnode2id int, rootid1 int, rootid2 int);
create table ggridtopology (id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, topologyid varchar(100), topologydescription varchar(150));
alter table gsites add COLUMN CLLICODE varchar(50);
alter table ggrids add vendor varchar(100), add vendorid varchar(150), add vendorgridname varchar(200);
drop table ggrids;
drop table ggridtopology;
drop table ggridnodes;
drop table ggridroots;
insert into ghregions (regionid, regiondescription) values ('Region1', 'NorthAmerica');
insert into gapptype (apptype, apptypedescription) values (2, 'Controller');
insert into gapptype (apptype, apptypedescription) values (1, 'Grid SSO');
insert into gapptype (apptype, apptypedescription) values (5, 'Simplex SSO');
insert into gapptype (apptype, apptypedescription) values (3, 'Gridified Web App');
insert into gapptype (apptype, apptypedescription) values (4, 'Gridified Mobile App');
insert into gapptype (apptype, apptypedescription) values (7, 'Simplex Mobile App');
insert into gapptype (apptype, apptypedescription) values (6, 'Simplex Web App');
insert into ggridtopology (topologyid, topologydescription) values ('T1+0', 'Triangle Active-Active-Active, No DR');
insert into ggridtopology (topologyid, topologydescription) values ('HA+0', 'HA Pair Active-Active, No DR');
insert into ggridtopology (topologyid, topologydescription) values ('M5+0', '5 NodeMesh, No DR');
insert into gsites (address1) values ('300main');
insert into gsites (address1) values ('1800 washington');
insert into gsites (address1) values ('Amazon Montreal DC');
insert into gsites (address1) values ('Google Iowa Cedar Rapids DC');
insert into gsites (address1) values ('Microsoft Seattle Azure DC West Original');
insert into ggridroots (siteid) VALUES (1);
insert into ggridroots (siteid) VALUES (2);
insert into ggridnodes (siteid) VALUES (1),(2), (3), (4), (5);
insert into ggrids (geometry) VALUES (3);

03/24 Was a Massive Day for GEM
create table gengineregions(id int GENERATED BY DEFAULT AS IDENTITY primary key, regiondescription varchar(100), regionid int);
create table gdbmsvendors (id int GENERATED BY DEFAULT AS IDENTITY primary key, vendorname varchar(100), vendorid varchar(100), dynamicsid varchar(100), oracleid varchar(100));
create table gdbmsreplication (id int GENERATED BY DEFAULT AS IDENTITY primary key, vendorname varchar(100), vendorid varchar(100), replicationdescription varchar(100));
create table gdbmsreleases (id int GENERATED BY DEFAULT AS IDENTITY primary key, vendorname varchar(100), vendorid varchar(100), releasedescription varchar(100), releaseversion varchar(100), releasesystemrequirements varchar(500));

insert into gdbmsvendors (vendorname) values ('ORACLE');
insert into gdbmsreplication (vendorname) values ('ORACLE');
insert into gdbmsreleases (vendorname) values ('ORACLE');
insert into gdbmstopology (dbmstopologydescription) values ('HAmirror + 0');
insert into gengineregions (regiondescription, regionid) VALUES ('NorthAmerica', 1), ('Canada', 2), ('CentralAmericaAndMexico', 3), ('SouthAmerica', 4), ('Europe', 5), ('MedittereanBasin', 6), ('Africa', 7), ('India', 8), ('CentralAsiaAndRussia', 9), ('SouthPacific',10), ('NorthPacific', 11);
create table gserviceorders(id int GENERATED BY DEFAULT AS IDENTITY primary key, regiondescription varchar(100), regionid int, ordertype int, custid varchar(100), orderdescription varchar(250), totalitems int);
insert into gserviceorders (regionid) VALUES (1);
create table gserviceordertype(id int GENERATED BY DEFAULT AS IDENTITY primary key, servicetypedescription varchar(100), servicetypeid int);
create table gserviceorderdetail(id bigint GENERATED BY DEFAULT AS IDENTITY primary key, skuid int, skuidc varchar(150), listcost varchar(25), unitcost varchar(25), statetax varchar(25), federalvat varchar(25));

03/26/25
create table gcompany(id bigint GENERATED BY DEFAULT AS IDENTITY primary key, companyname varchar(250), dynamicsid varchar(250), oracleid varchar(250), alohaid varchar(250));
create table gwholesalers(id bigint GENERATED BY DEFAULT AS IDENTITY primary key, wholesalename varchar(250), companyid int, dynamicsid varchar(250), oracleid varchar(250), alohaid varchar(250));
create table gaccounts(id bigint GENERATED BY DEFAULT AS IDENTITY primary key, accountname varchar(250), companyid int, wholesalevendorid int);
create table gusergroups (id bigint GENERATED BY DEFAULT AS IDENTITY primary key, groupname varchar(250), groupid varchar(100));
insert into gwholesalers (wholesalename) values ('CockyEnterprises');
insert into gaccounts (accountname) values ('University of South Carolina - Engineering');
insert into gcompany (companyname) values ('University of South Carolina - Master Account');
insert into gusergroups (groupname) values ('Administrators');
insert into gusergroups (groupname) values ('Noc Users');
insert into gusergroups (groupname) values ('Registered Users');
insert into gusergroups (groupname) values ('Super Users');




INSERT INTO GUSERS_CARDS (USERID,APPID) VALUES ('1','1');
INSERT INTO GPRODUCTS (PRODUCTNAME) VALUES('ISP1-YEAR-PERSONAL-GLOCATIONINFO');
INSERT INTO GPRODUCTS (PRODUCTNAME) VALUES('ISP1-YEAR-FAMILY-GLOCATIONINFO');
INSERT INTO GPRODUCTS (PRODUCTNAME) VALUES('BUSINESSPRO-VM-1YEAR-GLOCATIONINFO-100 USERS');
INSERT INTO GPRODUCTS (PRODUCTNAME) VALUES('PANELPLUS-VM-1YEAR-GLOCATIONINFO-25 USERS');
INSERT INTO GPRODUCTS (PRODUCTNAME) VALUES('PANELPLUS-VM-1YEAR-GLOCATIONINFO-100 USERS');
INSERT INTO GPRODUCTS (PRODUCTNAME) VALUES('ISP1-YEAR-TELEPRO-LITE-GLOCATIONINFO');
INSERT INTO GPRODUCTS (PRODUCTNAME) VALUES('ISP1-YEAR-PERSONAL-PARAMOUNTPLUS');
INSERT INTO GPRODUCTS (PRODUCTNAME) VALUES('ISP1-YEAR-PERSONAL-PEACOCKTV');
INSERT INTO GPRODUCTS (PRODUCTNAME) VALUES('ISP1-YEAR-PERSONAL-PREMIUM');
INSERT INTO GCHANGE VALUES(1, 'MEDIUM','CAPUS', 'JSSG33', 'FREEPBX HTML INSTERFACE INSTALL ON LOWELL.CAPITOLTECHNOLOGY.US', 'ERRORED-ST', 'NOCEXEC0003', '02/01/2020', '12/31/2022', 'NO HOLDS - NOT SERVICE IMPACING', 'WEIRD PHP PROBLEMS WHICH WE CANT EXPLAIN ON APACHE... PENDING MOVE TO NGINX');
INSERT INTO GCHANGE VALUES(2, 'SMALL','CAPUS', 'JSSG33', '3CX URL ADDS SSL INSTERFACE INSTALL ON DEBIAN1.CAPITOLTECHNOLOGY.US', 'ERRORED-ST', 'NOCEXEC0003', '02/01/2020', '12/31/2022', 'NO HOLDS - NOT SERVICE IMPACING', 'SSL SITE FOR NEW URL IS NEEDED, BUT UPSTREAM GW, CRASHES THE PRODUCTION WORK');
INSERT INTO GCHANGE VALUES(3, 'SMALL','CAPUS', 'JSSG33', '3CX URL ADDS SSL INSTERFACE INSTALL ON DEBIAN2.CAPITOLTECHNOLOGY.US', 'ERRORED-ST', 'NOCEXEC0003', '02/01/2020', '12/31/2022', 'NO HOLDS - NOT SERVICE IMPACING', 'SEE CHANGE2 COMMENTS');
INSERT INTO GCHANGE VALUES(4, 'SMALL','CAPUS', 'JSSG33', '3CX URL ADDS SSL INSTERFACE INSTALL ON DEBIAN3.CAPITOLTECHNOLOGY.US', 'ERRORED-ST', 'NOCEXEC0003', '02/01/2020', '12/31/2022', 'NO HOLDS - NOT SERVICE IMPACING', 'SEE CHANGE3 COMMENTS');
INSERT INTO GCHANGE VALUES(5, 'XLARGE','GLINFO', 'JSSG33', 'GL1.GLOCATION.INFO AUTOMATION PROVISIONING PRODUCT DETAIL INTERFACE INSTALL ON CHICAGO.CAPITOLTECHNOLOGY.US', 'ERRORED-ST', 'NOCEXEC0003', '02/01/2020', '12/31/2022', 'NO HOLDS - NOT SERVICE IMPACING', 'FRONTEND-PARTIALLY AUTOMATED WITH DUPLICATE INFO');
INSERT INTO GCHANGE VALUES(6, 'XLARGE','CAPUS', 'JSSG33', 'DNS MIGRATION TO CAPUS SERVERS', 'LONG-TERM', 'NOCEXEC0003', '02/01/2020', '12/31/2022', 'ONHOLD', 'ON HOLD FOR NC01-PROVISIONING');
INSERT INTO GCHANGE VALUES(7, 'XLARGE','GACOM', 'JSSG33', 'NC01 PROVISIONING', 'LONG-TERM', 'NOCEXEC0003', '02/01/2022', '12/31/2022', 'PLANNED', 'NC01 INSTALL AND HYPERV INSTALL ACROSS WAN');
INSERT INTO GCHANGE VALUES(8, 'XLARGE','GACOM', 'JSSG33', 'CA01 PROVISIONING', 'LONG-TERM', 'NOCEXEC0003', '02/01/2022', '12/31/2022', 'PLANNED', 'CA01 INSTALL AND HYPERV INSTALL ACROSS WAN');
INSERT INTO GITSM (CUSTID, ORACLEID, DYNAMICSID) VALUES('CAPUS-INTERNAL', 'CAPUS0001', 'CAPUS0001');
INSERT INTO GUSERS VALUES(2, 'JOHN', 'STRITZINGER', 'JOHNSTRITZINGER','843-352-3459', 'js@glocation.info', '1800 Washington Street', '#4', 'Columbia', 'SC', '29201', 'UNITEDSTATES', '843-352-3450', '1', '1', '1','1','1','1', '1', '1','1','1');
INSERT INTO GUSERS VALUES(1, 'JAMES', 'STRITZINGER', 'JAMESWSTRITZINGER','512-352-3459', 'jws@glocation.info', '1800 Washington Street', '#4', 'Columbia', 'SC', '29201', 'UNITEDSTATES', '512-352-3450', '1', '1', '1','1','1','1', '1', '1','1','1');

