create table gvoiceplatforms (id int GENERATED BY DEFAULT AS IDENTITY primary key, platformid varchar(150), platformtype int, description varchar(150), ipaddress varchar(50), telemetryipaddress varchar(50), vpnid1 varchar(50), vpnid2 varchar(50), serverid varchar(150));
create table gvoiceplatformtype (id int GENERATED BY DEFAULT AS IDENTITY primary key, platformtype int, description varchar(150));
create table gservers (id int GENERATED BY DEFAULT AS IDENTITY primary key, serverid varchar(150), description varchar(150), ipaddress varchar(50), telemetryipaddress varchar(50), vpnid1 varchar(50), vpnid2 varchar(50));
create table gfirewalls (id int GENERATED BY DEFAULT AS IDENTITY primary key, firewallid varchar(150), description varchar(150), ipaddress varchar(50), telemetryipaddress varchar(50), vpnid1 varchar(50), vpnid2 varchar(50));
create table gfirewallcontexts (id int GENERATED BY DEFAULT AS IDENTITY primary key, firewallid varchar(150), contextid varchar(150), description varchar(150), ipaddress varchar(50), telemetryipaddress varchar(50), vpnid1 varchar(50), vpnid2 varchar(50));
create table grouters (id int GENERATED BY DEFAULT AS IDENTITY primary key, routerid varchar(150), description varchar(150), ipaddress varchar(50), telemetryipaddress varchar(50), vpnid1 varchar(50), vpnid2 varchar(50));
create table gswitches (id int GENERATED BY DEFAULT AS IDENTITY primary key, switchid varchar(150), description varchar(150), ipaddress varchar(50), telemetryipaddress varchar(50), vpnid1 varchar(50), vpnid2 varchar(50));
create table gvoicegateway (id int GENERATED BY DEFAULT AS IDENTITY primary key, switchid varchar(150), description varchar(150), ipaddress varchar(50), telemetryipaddress varchar(50), vpnid1 varchar(50), vpnid2 varchar(50));
create table ghosts (id int GENERATED BY DEFAULT AS IDENTITY primary key, switchid varchar(150), serverid varchar(150), description varchar(150), ipaddress varchar(50), telemetryipaddress varchar(50), vpnid1 varchar(50), vpnid2 varchar(50), lpars int, imageid varchar(100));
create table ghostlpars (id int GENERATED BY DEFAULT AS IDENTITY primary key, lparid varchar(150), description varchar(150), ipaddress varchar(50), telemetryipaddress varchar(50), vpnid1 varchar(50), vpnid2 varchar(50));
create table ghostvms (id int GENERATED BY DEFAULT AS IDENTITY primary key, vmid varchar(150), description varchar(150), ipaddress varchar(50), telemetryipaddress varchar(50), vpnid1 varchar(50), vpnid2 varchar(50));
create table ghostimages (id int GENERATED BY DEFAULT AS IDENTITY primary key, imageid varchar(150), description varchar(150), imageurl varchar(150), imagevendor varchar(100), vendoraccountid varchar(100), operatingsystem varchar(100));
create table ggateways (id int GENERATED BY DEFAULT AS IDENTITY primary key, gatewayid varchar(150), gatewaytype int, description varchar(150), ipaddress varchar(50), telemetryipaddress varchar(50), vpnid1 varchar(50), vpnid2 varchar(50));
create table ggatewaytype (id int GENERATED BY DEFAULT AS IDENTITY primary key, type int, description varchar(150));
create table gsitetype (id int GENERATED BY DEFAULT AS IDENTITY primary key, sitetypeid int, description varchar(150));
create table gvoicetrunks (id int GENERATED BY DEFAULT AS IDENTITY primary key, trunkid varchar(150), trunktypeid int, description varchar(150));
create table gvoicetrunktype (id int GENERATED BY DEFAULT AS IDENTITY primary key, trunktypeid int, description varchar(150));
create table gcircuits (id int GENERATED BY DEFAULT AS IDENTITY primary key, circuittypeid int, description varchar(150), aloc varchar(150), zloc varchar(150));
create table gcircuittype (id int GENERATED BY DEFAULT AS IDENTITY primary key, circuittypeid int, description varchar(150));
create table gnetworks (id int GENERATED BY DEFAULT AS IDENTITY primary key, networkid int, networktypeid int, description varchar(150));
create table gnetworktype (id int GENERATED BY DEFAULT AS IDENTITY primary key, networktypeid int, description varchar(150));
create table gnetworksplicebox (id int GENERATED BY DEFAULT AS IDENTITY primary key, spliceid bigint, description varchar(150), gpslat varchar(100), gpslong varchar(100), user1 varchar(150), user2 varchar(150), user3 varchar(150), user4 varchar(150), user5 varchar(150));
create table gvendor(id int GENERATED BY DEFAULT AS IDENTITY primary key, vendorid varchar(100), vendorname varchar(150), vendoraddress1 varchar(100), vendoraddress2 varchar(100), vendorcity varchar(100), vendorstate varchar(100), vendorzip varchar(100)); 
create table gcpeother (id int GENERATED BY DEFAULT AS IDENTITY primary key, vendorid varchar(150), siteid int, description varchar(150), ipaddress varchar(50), telemetryipaddress varchar(50), vpnid1 varchar(50), vpnid2 varchar(50));
create table gfax (id int GENERATED BY DEFAULT AS IDENTITY primary key, faxid varchar(150), faxtype int, siteid int, description varchar(150), ipaddress varchar(50), telemetryipaddress varchar(50), vpnid1 varchar(50), vpnid2 varchar(50));
create table gphones (id int GENERATED BY DEFAULT AS IDENTITY primary key, phoneid varchar(150), phonetype int, siteid int, description varchar(150), ipaddress varchar(50), telemetryipaddress varchar(50), vpnid1 varchar(50), vpnid2 varchar(50), lat varchar(100), long varchar(100));
create table ghdvideo (id int GENERATED BY DEFAULT AS IDENTITY primary key, videoid varchar(150), vidtype int, siteid int, description varchar(150), ipaddress varchar(50), telemetryipaddress varchar(50), vpnid1 varchar(50), vpnid2 varchar(50));
create table gsecvideo (id int GENERATED BY DEFAULT AS IDENTITY primary key, videoid varchar(150), vidtype int, siteid int, description varchar(150), ipaddress varchar(50), telemetryipaddress varchar(50), vpnid1 varchar(50), vpnid2 varchar(50));
create table gcustomer (id int GENERATED BY DEFAULT AS IDENTITY primary key, description varchar(150), address1 varchar(100), address2 varchar(100), city varchar(100),state varchar(100), zip varchar(100), phone varchar(100));
create table gdisk (id int GENERATED BY DEFAULT AS IDENTITY primary key, diskid varchar(150), disktype int, machineid int, siteid int, serverid int, description varchar(150), ipaddress varchar(50), telemetryipaddress varchar(50), vpnid1 varchar(50), vpnid2 varchar(50), lat varchar(100), long varchar(100));
create table gdisktype (id int GENERATED BY DEFAULT AS IDENTITY primary key, disktype int, description varchar(150), vendorid varchar(100));
create table gopticalring (id int GENERATED BY DEFAULT AS IDENTITY primary key, ringid varchar(150), ringtype int, siteid1 int, siteid2 int, siteid3 int, siteid4 int, siteid5 int, vendorid int, description varchar(150), ipaddress varchar(50), telemetryipaddress varchar(50), vpnid1 varchar(50), vpnid2 varchar(50), lat varchar(100), long varchar(100));
create table gopttype( id int GENERATED BY DEFAULT AS IDENTITY primary key, opttypeid int, description varchar(150));
create table gcomputer (id int GENERATED BY DEFAULT AS IDENTITY primary key, computerid varchar(150), computertype int, siteid int, description varchar(150), ipaddress varchar(50), telemetryipaddress varchar(50), vpnid1 varchar(50), vpnid2 varchar(50));
create table gvolumes (id int GENERATED BY DEFAULT AS IDENTITY primary key, volumeid varchar(150), volumetype int, diskid int, description varchar(150));
create table gconduits (id int GENERATED BY DEFAULT AS IDENTITY primary key, conduitid varchar(150), conduittype int, rowid int, description varchar(150));
create table grightofway (id int GENERATED BY DEFAULT AS IDENTITY primary key, rowid int, rowtype int, description varchar(150));
create table gtelephonenumber (id int GENERATED BY DEFAULT AS IDENTITY primary key, tn varchar(100), phoneid int, channelid int, description varchar(150));
create table gcountry (id int GENERATED BY DEFAULT AS IDENTITY primary key, countryid varchar(100), exchange varchar(100), region varchar(100), description varchar(150));

x-no-links: 1
Content-type: text/html

