<html>
<head><title>CockyHRManager</title>
<style type="text/css">
.auto-style1 {
	text-align: center;
}
</style>
</head>
<body>
<div align="center">
<form id="form1" runat="server">
	<div class="auto-style1">
		<br>
		<asp:Image id="Image1" runat="server" ImageUrl="./cocky590.png" width="100px" height="100px"/>
		<br><br><br><br>COCKY ENTERPRISES <br>VOICE PLATFORMS <br><br>
		<div class="auto-style1">
			<asp:GridView id="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="id" DataSourceID="SqlDataSource1" Width="1408px" horizontalalign="Center" AllowPaging="True">
				<Columns>
					<asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" SortExpression="id">
					</asp:BoundField>
					<asp:BoundField DataField="platformid" HeaderText="platformid" SortExpression="platformid">
					</asp:BoundField>
					<asp:BoundField DataField="platformtype" HeaderText="platformtype" SortExpression="platformtype">
					</asp:BoundField>
					<asp:BoundField DataField="description" HeaderText="description" SortExpression="description">
					</asp:BoundField>
					<asp:BoundField DataField="ipaddress" HeaderText="ipaddress" SortExpression="ipaddress">
					</asp:BoundField>
					<asp:BoundField DataField="telemetryipaddress" HeaderText="telemetryipaddress" SortExpression="telemetryipaddress">
					</asp:BoundField>
					<asp:BoundField DataField="vpnid1" HeaderText="vpnid1" SortExpression="vpnid1">
					</asp:BoundField>
					<asp:BoundField DataField="vpnid2" HeaderText="vpnid2" SortExpression="vpnid2">
					</asp:BoundField>
					<asp:BoundField DataField="serverid" HeaderText="serverid" SortExpression="serverid">
					</asp:BoundField>
				</Columns>
			</asp:GridView>
		</div>
	</div>
	<asp:SqlDataSource id="SqlDataSource1" runat="server" ConflictDetection="CompareAllValues" ConnectionString="Dsn=GEMPROD" DeleteCommand="DELETE FROM [gvoiceplatforms] WHERE [id] = ? AND (([platformid] = ?) OR ([platformid] IS NULL AND ? IS NULL)) AND (([platformtype] = ?) OR ([platformtype] IS NULL AND ? IS NULL)) AND (([description] = ?) OR ([description] IS NULL AND ? IS NULL)) AND (([ipaddress] = ?) OR ([ipaddress] IS NULL AND ? IS NULL)) AND (([telemetryipaddress] = ?) OR ([telemetryipaddress] IS NULL AND ? IS NULL)) AND (([vpnid1] = ?) OR ([vpnid1] IS NULL AND ? IS NULL)) AND (([vpnid2] = ?) OR ([vpnid2] IS NULL AND ? IS NULL)) AND (([serverid] = ?) OR ([serverid] IS NULL AND ? IS NULL))" InsertCommand="INSERT INTO [gvoiceplatforms] ([platformid], [platformtype], [description], [ipaddress], [telemetryipaddress], [vpnid1], [vpnid2], [serverid]) VALUES (?, ?, ?, ?, ?, ?, ?, ?)" OldValuesParameterFormatString="original_{0}" ProviderName="System.Data.Odbc" SelectCommand="SELECT * FROM [gvoiceplatforms]" UpdateCommand="UPDATE [gvoiceplatforms] SET [platformid] = ?, [platformtype] = ?, [description] = ?, [ipaddress] = ?, [telemetryipaddress] = ?, [vpnid1] = ?, [vpnid2] = ?, [serverid] = ? WHERE [id] = ? AND (([platformid] = ?) OR ([platformid] IS NULL AND ? IS NULL)) AND (([platformtype] = ?) OR ([platformtype] IS NULL AND ? IS NULL)) AND (([description] = ?) OR ([description] IS NULL AND ? IS NULL)) AND (([ipaddress] = ?) OR ([ipaddress] IS NULL AND ? IS NULL)) AND (([telemetryipaddress] = ?) OR ([telemetryipaddress] IS NULL AND ? IS NULL)) AND (([vpnid1] = ?) OR ([vpnid1] IS NULL AND ? IS NULL)) AND (([vpnid2] = ?) OR ([vpnid2] IS NULL AND ? IS NULL)) AND (([serverid] = ?) OR ([serverid] IS NULL AND ? IS NULL))">
		<DeleteParameters>
			<asp:Parameter Name="original_id" Type="Int32" />
			<asp:Parameter Name="original_platformid" Type="String" />
			<asp:Parameter Name="original_platformid" Type="String" />
			<asp:Parameter Name="original_platformtype" Type="Int32" />
			<asp:Parameter Name="original_platformtype" Type="Int32" />
			<asp:Parameter Name="original_description" Type="String" />
			<asp:Parameter Name="original_description" Type="String" />
			<asp:Parameter Name="original_ipaddress" Type="String" />
			<asp:Parameter Name="original_ipaddress" Type="String" />
			<asp:Parameter Name="original_telemetryipaddress" Type="String" />
			<asp:Parameter Name="original_telemetryipaddress" Type="String" />
			<asp:Parameter Name="original_vpnid1" Type="String" />
			<asp:Parameter Name="original_vpnid1" Type="String" />
			<asp:Parameter Name="original_vpnid2" Type="String" />
			<asp:Parameter Name="original_vpnid2" Type="String" />
			<asp:Parameter Name="original_serverid" Type="String" />
			<asp:Parameter Name="original_serverid" Type="String" />
		</DeleteParameters>
		<InsertParameters>
			<asp:Parameter Name="platformid" Type="String" />
			<asp:Parameter Name="platformtype" Type="Int32" />
			<asp:Parameter Name="description" Type="String" />
			<asp:Parameter Name="ipaddress" Type="String" />
			<asp:Parameter Name="telemetryipaddress" Type="String" />
			<asp:Parameter Name="vpnid1" Type="String" />
			<asp:Parameter Name="vpnid2" Type="String" />
			<asp:Parameter Name="serverid" Type="String" />
		</InsertParameters>
		<UpdateParameters>
			<asp:Parameter Name="platformid" Type="String" />
			<asp:Parameter Name="platformtype" Type="Int32" />
			<asp:Parameter Name="description" Type="String" />
			<asp:Parameter Name="ipaddress" Type="String" />
			<asp:Parameter Name="telemetryipaddress" Type="String" />
			<asp:Parameter Name="vpnid1" Type="String" />
			<asp:Parameter Name="vpnid2" Type="String" />
			<asp:Parameter Name="serverid" Type="String" />
			<asp:Parameter Name="original_id" Type="Int32" />
			<asp:Parameter Name="original_platformid" Type="String" />
			<asp:Parameter Name="original_platformid" Type="String" />
			<asp:Parameter Name="original_platformtype" Type="Int32" />
			<asp:Parameter Name="original_platformtype" Type="Int32" />
			<asp:Parameter Name="original_description" Type="String" />
			<asp:Parameter Name="original_description" Type="String" />
			<asp:Parameter Name="original_ipaddress" Type="String" />
			<asp:Parameter Name="original_ipaddress" Type="String" />
			<asp:Parameter Name="original_telemetryipaddress" Type="String" />
			<asp:Parameter Name="original_telemetryipaddress" Type="String" />
			<asp:Parameter Name="original_vpnid1" Type="String" />
			<asp:Parameter Name="original_vpnid1" Type="String" />
			<asp:Parameter Name="original_vpnid2" Type="String" />
			<asp:Parameter Name="original_vpnid2" Type="String" />
			<asp:Parameter Name="original_serverid" Type="String" />
			<asp:Parameter Name="original_serverid" Type="String" />
		</UpdateParameters>
	</asp:SqlDataSource>
</form>
<span><a href="insertvoiceplatform.aspx">Insert a New Voice Platform</a><BR></span>
<BR>
<HR>
<span><a href="index.aspx">ReturnToManagerHome</a><BR></span>
<HR>
</div>
</body>
</html>