<html>
<head><title>CockyHRManager</title>
<style type="text/css">
.auto-style1 {
	text-align: center;
}
</style>
</head>
<body>
<div align="center">
<form id="form1" runat="server">
	<div class="auto-style1">
		<br>
		<asp:Image id="Image1" runat="server" ImageUrl="./cocky590.png" width="100px" height="100px"/>
		<br><br><br><br>COCKY ENTERPRISES <br>OUTSLIDE PLANT MANAGER <br><br>
		<div class="auto-style1">
			<asp:GridView id="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="id" DataSourceID="SqlDataSource1" Width="1408px" horizontalalign="Center" AllowPaging="True">
				<Columns>
					<asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" SortExpression="id">
					</asp:BoundField>
					<asp:BoundField DataField="spliceid" HeaderText="spliceid" SortExpression="spliceid">
					</asp:BoundField>
					<asp:BoundField DataField="description" HeaderText="description" SortExpression="description">
					</asp:BoundField>
					<asp:BoundField DataField="gpslat" HeaderText="gpslat" SortExpression="gpslat">
					</asp:BoundField>
					<asp:BoundField DataField="gpslong" HeaderText="gpslong" SortExpression="gpslong">
					</asp:BoundField>
					<asp:BoundField DataField="user1" HeaderText="user1" SortExpression="user1">
					</asp:BoundField>
					<asp:BoundField DataField="user2" HeaderText="user2" SortExpression="user2">
					</asp:BoundField>
					<asp:BoundField DataField="user3" HeaderText="user3" SortExpression="user3">
					</asp:BoundField>
					<asp:BoundField DataField="user4" HeaderText="user4" SortExpression="user4">
					</asp:BoundField>
					<asp:BoundField DataField="user5" HeaderText="user5" SortExpression="user5">
					</asp:BoundField>
				</Columns>
			</asp:GridView>
		</div>
	</div>
	<asp:SqlDataSource id="SqlDataSource1" runat="server" ConflictDetection="CompareAllValues" ConnectionString="Dsn=GEMPROD" DeleteCommand="DELETE FROM [gnetworksplicebox] WHERE [id] = ? AND (([spliceid] = ?) OR ([spliceid] IS NULL AND ? IS NULL)) AND (([description] = ?) OR ([description] IS NULL AND ? IS NULL)) AND (([gpslat] = ?) OR ([gpslat] IS NULL AND ? IS NULL)) AND (([gpslong] = ?) OR ([gpslong] IS NULL AND ? IS NULL)) AND (([user1] = ?) OR ([user1] IS NULL AND ? IS NULL)) AND (([user2] = ?) OR ([user2] IS NULL AND ? IS NULL)) AND (([user3] = ?) OR ([user3] IS NULL AND ? IS NULL)) AND (([user4] = ?) OR ([user4] IS NULL AND ? IS NULL)) AND (([user5] = ?) OR ([user5] IS NULL AND ? IS NULL))" InsertCommand="INSERT INTO [gnetworksplicebox] ([spliceid], [description], [gpslat], [gpslong], [user1], [user2], [user3], [user4], [user5]) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)" OldValuesParameterFormatString="original_{0}" ProviderName="System.Data.Odbc" SelectCommand="SELECT * FROM [gnetworksplicebox]" UpdateCommand="UPDATE [gnetworksplicebox] SET [spliceid] = ?, [description] = ?, [gpslat] = ?, [gpslong] = ?, [user1] = ?, [user2] = ?, [user3] = ?, [user4] = ?, [user5] = ? WHERE [id] = ? AND (([spliceid] = ?) OR ([spliceid] IS NULL AND ? IS NULL)) AND (([description] = ?) OR ([description] IS NULL AND ? IS NULL)) AND (([gpslat] = ?) OR ([gpslat] IS NULL AND ? IS NULL)) AND (([gpslong] = ?) OR ([gpslong] IS NULL AND ? IS NULL)) AND (([user1] = ?) OR ([user1] IS NULL AND ? IS NULL)) AND (([user2] = ?) OR ([user2] IS NULL AND ? IS NULL)) AND (([user3] = ?) OR ([user3] IS NULL AND ? IS NULL)) AND (([user4] = ?) OR ([user4] IS NULL AND ? IS NULL)) AND (([user5] = ?) OR ([user5] IS NULL AND ? IS NULL))">
		<DeleteParameters>
			<asp:Parameter Name="original_id" Type="Int32" />
			<asp:Parameter Name="original_spliceid" Type="Int64" />
			<asp:Parameter Name="original_spliceid" Type="Int64" />
			<asp:Parameter Name="original_description" Type="String" />
			<asp:Parameter Name="original_description" Type="String" />
			<asp:Parameter Name="original_gpslat" Type="String" />
			<asp:Parameter Name="original_gpslat" Type="String" />
			<asp:Parameter Name="original_gpslong" Type="String" />
			<asp:Parameter Name="original_gpslong" Type="String" />
			<asp:Parameter Name="original_user1" Type="String" />
			<asp:Parameter Name="original_user1" Type="String" />
			<asp:Parameter Name="original_user2" Type="String" />
			<asp:Parameter Name="original_user2" Type="String" />
			<asp:Parameter Name="original_user3" Type="String" />
			<asp:Parameter Name="original_user3" Type="String" />
			<asp:Parameter Name="original_user4" Type="String" />
			<asp:Parameter Name="original_user4" Type="String" />
			<asp:Parameter Name="original_user5" Type="String" />
			<asp:Parameter Name="original_user5" Type="String" />
		</DeleteParameters>
		<InsertParameters>
			<asp:Parameter Name="spliceid" Type="Int64" />
			<asp:Parameter Name="description" Type="String" />
			<asp:Parameter Name="gpslat" Type="String" />
			<asp:Parameter Name="gpslong" Type="String" />
			<asp:Parameter Name="user1" Type="String" />
			<asp:Parameter Name="user2" Type="String" />
			<asp:Parameter Name="user3" Type="String" />
			<asp:Parameter Name="user4" Type="String" />
			<asp:Parameter Name="user5" Type="String" />
		</InsertParameters>
		<UpdateParameters>
			<asp:Parameter Name="spliceid" Type="Int64" />
			<asp:Parameter Name="description" Type="String" />
			<asp:Parameter Name="gpslat" Type="String" />
			<asp:Parameter Name="gpslong" Type="String" />
			<asp:Parameter Name="user1" Type="String" />
			<asp:Parameter Name="user2" Type="String" />
			<asp:Parameter Name="user3" Type="String" />
			<asp:Parameter Name="user4" Type="String" />
			<asp:Parameter Name="user5" Type="String" />
			<asp:Parameter Name="original_id" Type="Int32" />
			<asp:Parameter Name="original_spliceid" Type="Int64" />
			<asp:Parameter Name="original_spliceid" Type="Int64" />
			<asp:Parameter Name="original_description" Type="String" />
			<asp:Parameter Name="original_description" Type="String" />
			<asp:Parameter Name="original_gpslat" Type="String" />
			<asp:Parameter Name="original_gpslat" Type="String" />
			<asp:Parameter Name="original_gpslong" Type="String" />
			<asp:Parameter Name="original_gpslong" Type="String" />
			<asp:Parameter Name="original_user1" Type="String" />
			<asp:Parameter Name="original_user1" Type="String" />
			<asp:Parameter Name="original_user2" Type="String" />
			<asp:Parameter Name="original_user2" Type="String" />
			<asp:Parameter Name="original_user3" Type="String" />
			<asp:Parameter Name="original_user3" Type="String" />
			<asp:Parameter Name="original_user4" Type="String" />
			<asp:Parameter Name="original_user4" Type="String" />
			<asp:Parameter Name="original_user5" Type="String" />
			<asp:Parameter Name="original_user5" Type="String" />
		</UpdateParameters>
	</asp:SqlDataSource>
</form>
<span><a href="insertsplicebox.aspx">Insert a New Splice Box</a><BR></span>
<BR>
<HR>
<span><a href="index.aspx">ReturnToManagerHome</a><BR></span>
<HR>
</div>
</body>
</html>