<html>
<head><title>CockyHRManager</title>
<style type="text/css">
.auto-style1 {
	text-align: center;
}
</style>
</head>
<body>
<div align="center">
<form id="form1" runat="server">
	<div class="auto-style1">
		<br>
		<asp:Image id="Image1" runat="server" ImageUrl="./cocky590.png" width="100px" height="100px"/>
		<br><br><br><br>COCKY ENTERPRISES <br>MANAGE CONDUITS<br><br>
		<div class="auto-style1">
			<asp:GridView id="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="id" DataSourceID="SqlDataSource1" Width="1408px" horizontalalign="Center" AllowPaging="True">
				<Columns>
					<asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" SortExpression="id">
					</asp:BoundField>
					<asp:BoundField DataField="conduitid" HeaderText="conduitid" SortExpression="conduitid">
					</asp:BoundField>
					<asp:BoundField DataField="conduittype" HeaderText="conduittype" SortExpression="conduittype">
					</asp:BoundField>
					<asp:BoundField DataField="rowid" HeaderText="rowid" SortExpression="rowid">
					</asp:BoundField>
					<asp:BoundField DataField="description" HeaderText="description" SortExpression="description">
					</asp:BoundField>
				</Columns>
			</asp:GridView>
		</div>
	</div>
	<asp:SqlDataSource id="SqlDataSource1" runat="server" ConflictDetection="CompareAllValues" ConnectionString="Dsn=GEM32" DeleteCommand="DELETE FROM [gconduits] WHERE [id] = ? AND (([conduitid] = ?) OR ([conduitid] IS NULL AND ? IS NULL)) AND (([conduittype] = ?) OR ([conduittype] IS NULL AND ? IS NULL)) AND (([rowid] = ?) OR ([rowid] IS NULL AND ? IS NULL)) AND (([description] = ?) OR ([description] IS NULL AND ? IS NULL))" InsertCommand="INSERT INTO [gconduits] ([conduitid], [conduittype], [rowid], [description]) VALUES (?, ?, ?, ?)" OldValuesParameterFormatString="original_{0}" ProviderName="System.Data.Odbc" SelectCommand="SELECT * FROM [gconduits]" UpdateCommand="UPDATE [gconduits] SET [conduitid] = ?, [conduittype] = ?, [rowid] = ?, [description] = ? WHERE [id] = ? AND (([conduitid] = ?) OR ([conduitid] IS NULL AND ? IS NULL)) AND (([conduittype] = ?) OR ([conduittype] IS NULL AND ? IS NULL)) AND (([rowid] = ?) OR ([rowid] IS NULL AND ? IS NULL)) AND (([description] = ?) OR ([description] IS NULL AND ? IS NULL))">
		<DeleteParameters>
			<asp:Parameter Name="original_id" Type="Int32" />
			<asp:Parameter Name="original_conduitid" Type="String" />
			<asp:Parameter Name="original_conduitid" Type="String" />
			<asp:Parameter Name="original_conduittype" Type="Int32" />
			<asp:Parameter Name="original_conduittype" Type="Int32" />
			<asp:Parameter Name="original_rowid" Type="Int32" />
			<asp:Parameter Name="original_rowid" Type="Int32" />
			<asp:Parameter Name="original_description" Type="String" />
			<asp:Parameter Name="original_description" Type="String" />
		</DeleteParameters>
		<InsertParameters>
			<asp:Parameter Name="conduitid" Type="String" />
			<asp:Parameter Name="conduittype" Type="Int32" />
			<asp:Parameter Name="rowid" Type="Int32" />
			<asp:Parameter Name="description" Type="String" />
		</InsertParameters>
		<UpdateParameters>
			<asp:Parameter Name="conduitid" Type="String" />
			<asp:Parameter Name="conduittype" Type="Int32" />
			<asp:Parameter Name="rowid" Type="Int32" />
			<asp:Parameter Name="description" Type="String" />
			<asp:Parameter Name="original_id" Type="Int32" />
			<asp:Parameter Name="original_conduitid" Type="String" />
			<asp:Parameter Name="original_conduitid" Type="String" />
			<asp:Parameter Name="original_conduittype" Type="Int32" />
			<asp:Parameter Name="original_conduittype" Type="Int32" />
			<asp:Parameter Name="original_rowid" Type="Int32" />
			<asp:Parameter Name="original_rowid" Type="Int32" />
			<asp:Parameter Name="original_description" Type="String" />
			<asp:Parameter Name="original_description" Type="String" />
		</UpdateParameters>
	</asp:SqlDataSource>
</form>
<span><a href="insertconduit.aspx">Insert a New Conduit</a><BR></span>
<BR>
<HR>
<span><a href="index.aspx">ReturnToManagerHome</a><BR></span>
<HR>
</div>
</body>
</html>