<html>
<head><title>CockyHRManager</title>
<style type="text/css">
.auto-style1 {
	text-align: center;
}
</style>
</head>
<body>
<div align="center">
<form id="form1" runat="server">
	<div class="auto-style1">
		<br>
		<asp:Image id="Image1" runat="server" ImageUrl="./cocky590.png" width="100px" height="100px"/>
		<br><br><br><br>COCKY ENTERPRISES <br>WHOLESALE COMPANY MANAGER <br><br>
		<div class="auto-style1">
			<asp:GridView id="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="id" DataSourceID="SqlDataSource1" Width="1408px" horizontalalign="Center" AllowPaging="True">
				<Columns>
					<asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" SortExpression="id">
					</asp:BoundField>
					<asp:BoundField DataField="wholesalename" HeaderText="wholesalename" SortExpression="wholesalename">
					</asp:BoundField>
					<asp:BoundField DataField="companyid" HeaderText="companyid" SortExpression="companyid">
					</asp:BoundField>
					<asp:BoundField DataField="dynamicsid" HeaderText="dynamicsid" SortExpression="dynamicsid">
					</asp:BoundField>
					<asp:BoundField DataField="oracleid" HeaderText="oracleid" SortExpression="oracleid">
					</asp:BoundField>
					<asp:BoundField DataField="alohaid" HeaderText="alohaid" SortExpression="alohaid">
					</asp:BoundField>
				</Columns>
			</asp:GridView>
		</div>
	</div>
	<asp:SqlDataSource id="SqlDataSource1" runat="server" ConflictDetection="CompareAllValues" ConnectionString="Dsn=GEMPROD" DeleteCommand="DELETE FROM [gwholesalers] WHERE [id] = ? AND (([wholesalename] = ?) OR ([wholesalename] IS NULL AND ? IS NULL)) AND (([companyid] = ?) OR ([companyid] IS NULL AND ? IS NULL)) AND (([dynamicsid] = ?) OR ([dynamicsid] IS NULL AND ? IS NULL)) AND (([oracleid] = ?) OR ([oracleid] IS NULL AND ? IS NULL)) AND (([alohaid] = ?) OR ([alohaid] IS NULL AND ? IS NULL))" InsertCommand="INSERT INTO [gwholesalers] ([wholesalename], [companyid], [dynamicsid], [oracleid], [alohaid]) VALUES (?, ?, ?, ?, ?)" OldValuesParameterFormatString="original_{0}" ProviderName="System.Data.Odbc" SelectCommand="SELECT * FROM [gwholesalers]" UpdateCommand="UPDATE [gwholesalers] SET [wholesalename] = ?, [companyid] = ?, [dynamicsid] = ?, [oracleid] = ?, [alohaid] = ? WHERE [id] = ? AND (([wholesalename] = ?) OR ([wholesalename] IS NULL AND ? IS NULL)) AND (([companyid] = ?) OR ([companyid] IS NULL AND ? IS NULL)) AND (([dynamicsid] = ?) OR ([dynamicsid] IS NULL AND ? IS NULL)) AND (([oracleid] = ?) OR ([oracleid] IS NULL AND ? IS NULL)) AND (([alohaid] = ?) OR ([alohaid] IS NULL AND ? IS NULL))">
		<DeleteParameters>
			<asp:Parameter Name="original_id" Type="Int64" />
			<asp:Parameter Name="original_wholesalename" Type="String" />
			<asp:Parameter Name="original_wholesalename" Type="String" />
			<asp:Parameter Name="original_companyid" Type="Int32" />
			<asp:Parameter Name="original_companyid" Type="Int32" />
			<asp:Parameter Name="original_dynamicsid" Type="String" />
			<asp:Parameter Name="original_dynamicsid" Type="String" />
			<asp:Parameter Name="original_oracleid" Type="String" />
			<asp:Parameter Name="original_oracleid" Type="String" />
			<asp:Parameter Name="original_alohaid" Type="String" />
			<asp:Parameter Name="original_alohaid" Type="String" />
		</DeleteParameters>
		<InsertParameters>
			<asp:Parameter Name="wholesalename" Type="String" />
			<asp:Parameter Name="companyid" Type="Int32" />
			<asp:Parameter Name="dynamicsid" Type="String" />
			<asp:Parameter Name="oracleid" Type="String" />
			<asp:Parameter Name="alohaid" Type="String" />
		</InsertParameters>
		<UpdateParameters>
			<asp:Parameter Name="wholesalename" Type="String" />
			<asp:Parameter Name="companyid" Type="Int32" />
			<asp:Parameter Name="dynamicsid" Type="String" />
			<asp:Parameter Name="oracleid" Type="String" />
			<asp:Parameter Name="alohaid" Type="String" />
			<asp:Parameter Name="original_id" Type="Int64" />
			<asp:Parameter Name="original_wholesalename" Type="String" />
			<asp:Parameter Name="original_wholesalename" Type="String" />
			<asp:Parameter Name="original_companyid" Type="Int32" />
			<asp:Parameter Name="original_companyid" Type="Int32" />
			<asp:Parameter Name="original_dynamicsid" Type="String" />
			<asp:Parameter Name="original_dynamicsid" Type="String" />
			<asp:Parameter Name="original_oracleid" Type="String" />
			<asp:Parameter Name="original_oracleid" Type="String" />
			<asp:Parameter Name="original_alohaid" Type="String" />
			<asp:Parameter Name="original_alohaid" Type="String" />
		</UpdateParameters>
	</asp:SqlDataSource>
</form>
<span><a href="insertwholesaleaccount.aspx">Insert a New Wholesale Account</a><BR></span>
<BR>
<HR>
<span><a href="index.aspx">ReturnToManagerHome</a><BR></span>
<HR>
</div>
</body>
</html>