<html>
<head><title>CockyHRManager</title>
<style type="text/css">
.auto-style1 {
	text-align: center;
}
</style>
</head>
<body>
<div align="center">
<form id="form1" runat="server">
	<div class="auto-style1">
		<br>
		<asp:Image id="Image1" runat="server" ImageUrl="./cocky590.png" width="100px" height="100px"/>
		<br><br><br><br>COCKY ENTERPRISES OFFICER ADMINISTRATOR<br><br>
		<div class="auto-style1">
			<asp:GridView id="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="id" DataSourceID="SqlDataSource1" Width="1408px" horizontalalign="Center" AllowPaging="True">
				<Columns>
					<asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" SortExpression="id">
					</asp:BoundField>
					<asp:BoundField DataField="managerid" HeaderText="managerid" SortExpression="managerid">
					</asp:BoundField>
					<asp:BoundField DataField="fullname" HeaderText="fullname" SortExpression="fullname">
					</asp:BoundField>
				</Columns>
			</asp:GridView>
		</div>
	</div>
	<asp:SqlDataSource id="SqlDataSource1" runat="server" ConflictDetection="CompareAllValues" ConnectionString="Dsn=GEMPROD" DeleteCommand="DELETE FROM [gmanagers] WHERE [id] = ? AND (([managerid] = ?) OR ([managerid] IS NULL AND ? IS NULL)) AND (([fullname] = ?) OR ([fullname] IS NULL AND ? IS NULL))" InsertCommand="INSERT INTO [gmanagers] ([managerid], [fullname]) VALUES (?, ?)" OldValuesParameterFormatString="original_{0}" ProviderName="System.Data.Odbc" SelectCommand="SELECT * FROM [gmanagers]" UpdateCommand="UPDATE [gmanagers] SET [managerid] = ?, [fullname] = ? WHERE [id] = ? AND (([managerid] = ?) OR ([managerid] IS NULL AND ? IS NULL)) AND (([fullname] = ?) OR ([fullname] IS NULL AND ? IS NULL))">
		<DeleteParameters>
			<asp:Parameter Name="original_id" Type="Int32" />
			<asp:Parameter Name="original_managerid" Type="String" />
			<asp:Parameter Name="original_managerid" Type="String" />
			<asp:Parameter Name="original_fullname" Type="String" />
			<asp:Parameter Name="original_fullname" Type="String" />
		</DeleteParameters>
		<InsertParameters>
			<asp:Parameter Name="managerid" Type="String" />
			<asp:Parameter Name="fullname" Type="String" />
		</InsertParameters>
		<UpdateParameters>
			<asp:Parameter Name="managerid" Type="String" />
			<asp:Parameter Name="fullname" Type="String" />
			<asp:Parameter Name="original_id" Type="Int32" />
			<asp:Parameter Name="original_managerid" Type="String" />
			<asp:Parameter Name="original_managerid" Type="String" />
			<asp:Parameter Name="original_fullname" Type="String" />
			<asp:Parameter Name="original_fullname" Type="String" />
		</UpdateParameters>
	</asp:SqlDataSource>
</form>
<span><a href="insertmanager.aspx">Insert a New Manager</a><BR></span>
<BR>
<HR>
<span><a href="index.aspx">ReturnToManagerHome</a><BR></span>
<HR>
</div>
</body>
</html>