<html>
<head><title>CockyHRManager</title>
<style type="text/css">
.auto-style1 {
	text-align: center;
}
</style>
</head>
<body>
<div align="center">
<form id="form1" runat="server">
	<div class="auto-style1">
		<br>
		<asp:Image id="Image1" runat="server" ImageUrl="./cocky590.png" width="100px" height="100px"/>
		<br><br><br><br>COCKY ENTERPRISES HOSTING MANAGER <br><br>
		<div class="auto-style1">
			<asp:GridView id="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="id" DataSourceID="SqlDataSource1" Width="1408px" horizontalalign="Center" AllowPaging="True">
				<Columns>
					<asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" SortExpression="id">
					</asp:BoundField>
					<asp:BoundField DataField="regionid" HeaderText="regionid" SortExpression="regionid">
					</asp:BoundField>
					<asp:BoundField DataField="regiondescription" HeaderText="regiondescription" SortExpression="regiondescription">
					</asp:BoundField>
				</Columns>
			</asp:GridView>
		</div>
	</div>
	<asp:SqlDataSource id="SqlDataSource1" runat="server" ConflictDetection="CompareAllValues" ConnectionString="Dsn=GEMPROD" DeleteCommand="DELETE FROM [ghregions] WHERE [id] = ? AND (([regionid] = ?) OR ([regionid] IS NULL AND ? IS NULL)) AND (([regiondescription] = ?) OR ([regiondescription] IS NULL AND ? IS NULL))" InsertCommand="INSERT INTO [ghregions] ([regionid], [regiondescription]) VALUES (?, ?)" OldValuesParameterFormatString="original_{0}" ProviderName="System.Data.Odbc" SelectCommand="SELECT * FROM [ghregions]" UpdateCommand="UPDATE [ghregions] SET [regionid] = ?, [regiondescription] = ? WHERE [id] = ? AND (([regionid] = ?) OR ([regionid] IS NULL AND ? IS NULL)) AND (([regiondescription] = ?) OR ([regiondescription] IS NULL AND ? IS NULL))">
		<DeleteParameters>
			<asp:Parameter Name="original_id" Type="Int32" />
			<asp:Parameter Name="original_regionid" Type="String" />
			<asp:Parameter Name="original_regionid" Type="String" />
			<asp:Parameter Name="original_regiondescription" Type="String" />
			<asp:Parameter Name="original_regiondescription" Type="String" />
		</DeleteParameters>
		<InsertParameters>
			<asp:Parameter Name="regionid" Type="String" />
			<asp:Parameter Name="regiondescription" Type="String" />
		</InsertParameters>
		<UpdateParameters>
			<asp:Parameter Name="regionid" Type="String" />
			<asp:Parameter Name="regiondescription" Type="String" />
			<asp:Parameter Name="original_id" Type="Int32" />
			<asp:Parameter Name="original_regionid" Type="String" />
			<asp:Parameter Name="original_regionid" Type="String" />
			<asp:Parameter Name="original_regiondescription" Type="String" />
			<asp:Parameter Name="original_regiondescription" Type="String" />
		</UpdateParameters>
	</asp:SqlDataSource>
</form>
<span><a href="inserthregion.aspx">Insert a Hosting Region</a><BR></span>
<BR>
<HR>
<span><a href="index.aspx">ReturnToManagerHome</a><BR></span>
<HR>
</div>
</body>
</html>