<html>
<head><title>CockyHRManager</title>
<style type="text/css">
.auto-style1 {
	text-align: center;
}
</style>
</head>
<body>
<div align="center">
<form id="form1" runat="server">
	<div class="auto-style1">
		<br>
		<asp:Image id="Image1" runat="server" ImageUrl="./cocky590.png" width="100px" height="100px"/>
		<br><br><br><br>COCKY ENTERPRISES GRID ROOTS<br><br>
		<div class="auto-style1">
			<asp:GridView id="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="id" DataSourceID="SqlDataSource1" Width="1408px" horizontalalign="Center" AllowPaging="True">
				<Columns>
					<asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" SortExpression="id" InsertVisible="False">
					</asp:BoundField>
					<asp:BoundField DataField="siteid" HeaderText="siteid" SortExpression="siteid">
					</asp:BoundField>
					<asp:BoundField DataField="rackid" HeaderText="rackid" SortExpression="rackid">
					</asp:BoundField>
					<asp:BoundField DataField="locationid" HeaderText="locationid" SortExpression="locationid">
					</asp:BoundField>
					<asp:BoundField DataField="floorid" HeaderText="floorid" SortExpression="floorid">
					</asp:BoundField>
					<asp:BoundField DataField="ipaddress" HeaderText="ipaddress" SortExpression="ipaddress">
					</asp:BoundField>
					<asp:BoundField DataField="telemetryip" HeaderText="telemetryip" SortExpression="telemetryip">
					</asp:BoundField>
				</Columns>
			</asp:GridView>
		</div>
	</div>
	<asp:SqlDataSource id="SqlDataSource1" runat="server" ConflictDetection="CompareAllValues" ConnectionString="Dsn=GEMPROD" DeleteCommand="DELETE FROM [ggridroots] WHERE [id] = ? AND (([siteid] = ?) OR ([siteid] IS NULL AND ? IS NULL)) AND (([rackid] = ?) OR ([rackid] IS NULL AND ? IS NULL)) AND (([locationid] = ?) OR ([locationid] IS NULL AND ? IS NULL)) AND (([floorid] = ?) OR ([floorid] IS NULL AND ? IS NULL)) AND (([ipaddress] = ?) OR ([ipaddress] IS NULL AND ? IS NULL)) AND (([telemetryip] = ?) OR ([telemetryip] IS NULL AND ? IS NULL))" InsertCommand="INSERT INTO [ggridroots] ([siteid], [rackid], [locationid], [floorid], [ipaddress], [telemetryip]) VALUES (?, ?, ?, ?, ?, ?)" OldValuesParameterFormatString="original_{0}" ProviderName="System.Data.Odbc" SelectCommand="SELECT * FROM [ggridroots]" UpdateCommand="UPDATE [ggridroots] SET [siteid] = ?, [rackid] = ?, [locationid] = ?, [floorid] = ?, [ipaddress] = ?, [telemetryip] = ? WHERE [id] = ? AND (([siteid] = ?) OR ([siteid] IS NULL AND ? IS NULL)) AND (([rackid] = ?) OR ([rackid] IS NULL AND ? IS NULL)) AND (([locationid] = ?) OR ([locationid] IS NULL AND ? IS NULL)) AND (([floorid] = ?) OR ([floorid] IS NULL AND ? IS NULL)) AND (([ipaddress] = ?) OR ([ipaddress] IS NULL AND ? IS NULL)) AND (([telemetryip] = ?) OR ([telemetryip] IS NULL AND ? IS NULL))">
		<DeleteParameters>
			<asp:Parameter Name="original_id" Type="Int32" />
			<asp:Parameter Name="original_siteid" Type="Int32" />
			<asp:Parameter Name="original_siteid" Type="Int32" />
			<asp:Parameter Name="original_rackid" Type="Int32" />
			<asp:Parameter Name="original_rackid" Type="Int32" />
			<asp:Parameter Name="original_locationid" Type="Int32" />
			<asp:Parameter Name="original_locationid" Type="Int32" />
			<asp:Parameter Name="original_floorid" Type="Int32" />
			<asp:Parameter Name="original_floorid" Type="Int32" />
			<asp:Parameter Name="original_ipaddress" Type="String" />
			<asp:Parameter Name="original_ipaddress" Type="String" />
			<asp:Parameter Name="original_telemetryip" Type="String" />
			<asp:Parameter Name="original_telemetryip" Type="String" />
		</DeleteParameters>
		<InsertParameters>
			<asp:Parameter Name="siteid" Type="Int32" />
			<asp:Parameter Name="rackid" Type="Int32" />
			<asp:Parameter Name="locationid" Type="Int32" />
			<asp:Parameter Name="floorid" Type="Int32" />
			<asp:Parameter Name="ipaddress" Type="String" />
			<asp:Parameter Name="telemetryip" Type="String" />
		</InsertParameters>
		<UpdateParameters>
			<asp:Parameter Name="siteid" Type="Int32" />
			<asp:Parameter Name="rackid" Type="Int32" />
			<asp:Parameter Name="locationid" Type="Int32" />
			<asp:Parameter Name="floorid" Type="Int32" />
			<asp:Parameter Name="ipaddress" Type="String" />
			<asp:Parameter Name="telemetryip" Type="String" />
			<asp:Parameter Name="original_id" Type="Int32" />
			<asp:Parameter Name="original_siteid" Type="Int32" />
			<asp:Parameter Name="original_siteid" Type="Int32" />
			<asp:Parameter Name="original_rackid" Type="Int32" />
			<asp:Parameter Name="original_rackid" Type="Int32" />
			<asp:Parameter Name="original_locationid" Type="Int32" />
			<asp:Parameter Name="original_locationid" Type="Int32" />
			<asp:Parameter Name="original_floorid" Type="Int32" />
			<asp:Parameter Name="original_floorid" Type="Int32" />
			<asp:Parameter Name="original_ipaddress" Type="String" />
			<asp:Parameter Name="original_ipaddress" Type="String" />
			<asp:Parameter Name="original_telemetryip" Type="String" />
			<asp:Parameter Name="original_telemetryip" Type="String" />
		</UpdateParameters>
	</asp:SqlDataSource>
</form>
<span><a href="insertgridroot.aspx">Insert a New Grid Root</a><BR></span>
<BR>
<HR>
<span><a href="index.aspx">ReturnToManagerHome</a><BR></span>
<HR>
</div>
</body>
</html>