create table Gsoftwarelicenses  (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, licenseid varchar(150), description varchar(150), licensetypeid int, vendorid int, startdate date, enddate date, notificatedate date, alertemail varchar(150), technicalcontact id, gridid int, totalseats int);
create table Glicensetype  (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, licensetypeid int, description varchar(150), term varchar(150));
alter table gapps add licensetype int;
alter table gapps add licenseexpiration;
alter table gapps add licenseid;


